### ISSUE TITLE
autofocus does not seem to work

### ISSUE THREAD

**Issue by mark8044** [nlfiedler/choose_input_chips#13]
I have an `ChipsInput` within a scrollable `Column` and as soon as the ChipsInput comes into view the keyboard pops up.  I've tried to set `autofocus` to `false` but it doesn't seem to have any effect

This is on Flutter 3.10.0

**Comment by BurningAXE** [comment]
@nlfiedler I believe I have found the problem & solution - can I get permission to raise a PR?

**Comment by nlfiedler** [comment]
Why am I not getting emails when issues are filed? Sorry about not seeing this sooner.

@BurningAXE Yes please, no permission required, please go ahead. Thank you.

**Comment by BurningAXE** [comment]
@nlfiedler I tried but the request got rejected because I don't have permissions.

**Comment by nlfiedler** [comment]
I think this repo is broken, I will have to recreate it from scratch. It was originally just a fork, but I requested the "unfork" operation and that seems have left this repo in a bad state. All of the settings match exactly with my other repos that are working correctly, so it must be some hidden flag that is breaking this one.

**Comment by nlfiedler** [comment]
It is not going well. I can create another repo in GH but the push of the repository is hanging in the middle. I've left it running for two hours and it seems to be thoroughly stuck. I'm running out of options, other than destroy everything, including the history, and push a shallow copy.

**Comment by nlfiedler** [comment]
I can push to gitlab, and in the mean time I have created a GH support ticket. The GL link is https://gitlab.com/nlfiedler1/choose_input_chips (why "1" I have no idea).

**Comment by nlfiedler** [comment]
@BurningAXE Okay, I've confirmed that fork and PR should be working fine. Can you send me the error message that you are seeing?

**Comment by BurningAXE** [comment]
> Can't create a new pull request: Push failed: remote: Permission to nlfiedler/choose_input_chips.git denied to BurningAXE. unable to access 'https://github.com/nlfiedler/choose_input_chips.git/': The requested URL returned error: 403
This is from Android Studio when trying to create a branch. Or do I necessarily need to fork it and raise a PR from the fork?

**Comment by nlfiedler** [comment]
Okay, sounds like a tools issue. AFAIK, you need to press the Fork button on the web site first, `git clone` from your fork, and then you can make changes and submit a PR. If you were a "collaborator" on the project, then perhaps Studio would work as expected.

**Comment by mark8044** [comment]
@nlfiedler @BurningAXE Any update? :)
